
/*
** JOEBASE - The Action Figure Database
** joebase-series-initialize: This file loads the series table values.
**
** The series table is not a straight lookup table, but a table of manufacturer-associated series
** identifiers. A single series name may be used by multiple manufacturers.
**
** Copyright Leonard Armstrong, 2018
** IST659
*/

USE joebase;

----------------------------------------------------------------------------------------------------
-- DELETE SECTION
-- Ensure the table is clean before (re)initializing.
----------------------------------------------------------------------------------------------------

DELETE FROM series;
GO

----------------------------------------------------------------------------------------------------
-- DATA INITIALIZATION SECTION
-- Values were generated by running a complex concatenation function on the unique set of
-- manufacturer/series combinations in the original Joebase Excel spreadsheet.
----------------------------------------------------------------------------------------------------

INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'America''s Finest', NULL FROM manufacturer m WHERE m.manufacturer_name = '21st Century Toys'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Convention Exclusive', NULL FROM manufacturer m WHERE m.manufacturer_name = '21st Century Toys'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'The Villains', NULL FROM manufacturer m WHERE m.manufacturer_name = '21st Century Toys'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Ultimate Soldier', NULL FROM manufacturer m WHERE m.manufacturer_name = '21st Century Toys'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Most Wanted', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Armoury'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Cy Girls', NULL FROM manufacturer m WHERE m.manufacturer_name = 'bbi'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Elite Force', NULL FROM manufacturer m WHERE m.manufacturer_name = 'bbi'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Elite Force Aviator', NULL FROM manufacturer m WHERE m.manufacturer_name = 'bbi'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Elite Force WWII', NULL FROM manufacturer m WHERE m.manufacturer_name = 'bbi'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Perfect Dark', NULL FROM manufacturer m WHERE m.manufacturer_name = 'bbi'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'G.I. Joe', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Chronicle Books'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Masterpiece Edition', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Chronicle Books'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Eiite Brigade Armor', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Cotswold Collectibles'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Elite Brigade', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Cotswold Collectibles'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Action Diver', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Custom'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Action Patriarch', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Custom'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'G.I. Elic', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Custom'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'G.I. Joe', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Custom'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, '1:6 Scale Deluxe Collector Figure', NULL FROM manufacturer m WHERE m.manufacturer_name = 'DC Direct'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, '13" Deluxe Collector Figure', NULL FROM manufacturer m WHERE m.manufacturer_name = 'DC Direct'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'World War II', NULL FROM manufacturer m WHERE m.manufacturer_name = 'DiD'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Danger Girl', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Dragon'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Gulf War', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Dragon'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Korean War', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Dragon'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Nam', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Dragon'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'New Century Elite', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Dragon'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'World War II', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Dragon'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Leaders of WWII', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Drastic Plastic'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Series 1', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Drastic Plastic'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Action Marine', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Dreams and Visions'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Action Pilot', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Dreams and Visions'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Action Sailor', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Dreams and Visions'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Action Soldier', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Dreams and Visions'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Crewcut Edition', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Dreams and Visions'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'D.C. Comics', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Dreams and Visions'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'G.I. Joe', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Dreams and Visions'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Real Heroes', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Ertl'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Captain Action', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Forever Fun'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Soldiers of the World', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Formative'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'World War II', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Formative'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Action Sailor', NULL FROM manufacturer m WHERE m.manufacturer_name = 'G.I. Joe Collector''s Club'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Action Soldier', NULL FROM manufacturer m WHERE m.manufacturer_name = 'G.I. Joe Collector''s Club'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Adventure Team', NULL FROM manufacturer m WHERE m.manufacturer_name = 'G.I. Joe Collector''s Club'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Adventures of G.I. Joe', NULL FROM manufacturer m WHERE m.manufacturer_name = 'G.I. Joe Collector''s Club'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Convention Exclusive', NULL FROM manufacturer m WHERE m.manufacturer_name = 'G.I. Joe Collector''s Club'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'G.I. Joe', NULL FROM manufacturer m WHERE m.manufacturer_name = 'G.I. Joe Collector''s Club'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'G.I. Joe Collector''s Club Membership', NULL FROM manufacturer m WHERE m.manufacturer_name = 'G.I. Joe Collector''s Club'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, '35th Anniversary', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Hasbro'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, '40th Anniversay Edition', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Hasbro'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'A Real American Hero', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Hasbro'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Action Marine', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Hasbro'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Action Pilot', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Hasbro'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Action Sailor', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Hasbro'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Action Soldier', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Hasbro'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Action Soldiers of the World', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Hasbro'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Adventure Team', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Hasbro'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Adventures of G.I. Joe', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Hasbro'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Adventures of G.I. Joe 2010', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Hasbro'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Army Rangers Collection', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Hasbro'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Classic Collection', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Hasbro'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'D-Day Collection', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Hasbro'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Echo Assortment', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Hasbro'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Foreign Soldiers Collection', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Hasbro'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'G.I. Joe', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Hasbro'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'G.I. Joe vs. Cobra', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Hasbro'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Historical Commanders Edition', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Hasbro'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Historical Editions', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Hasbro'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Navy Seals Collection', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Hasbro'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Pearl Harbor Collection', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Hasbro'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Spy Troops', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Hasbro'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Timeless Collection', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Hasbro'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Valor vs Venom', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Hasbro'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Batman 1966', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Hot Toys'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Batman v. Superman', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Hot Toys'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'D.C. Comics', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Hot Toys'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Movie Masterpiece Series', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Hot Toys'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Star Wars', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Hot Toys'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'The Dark Knight Rises', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Hot Toys'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Action Boy', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Ideal'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Captain Action', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Ideal'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Uniform and Equipment', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Ideal'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'War Criminals of the 20th Century', NULL FROM manufacturer m WHERE m.manufacturer_name = 'In the Past Toys'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Federation Fighters', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Jakks Pacific'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Ringside Rebels', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Jakks Pacific'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Series 2', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Jakks Pacific'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Action Man', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Kenner'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Classic Collection', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Kenner'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'G.I. Joe', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Kenner'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Historical Commanders Edition', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Kenner'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Hollywood Heroes Collection', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Kenner'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Modern Forces Assortment', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Kenner'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Star Wars', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Kenner'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'The Original Trilogy Collection', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Kenner'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Timeless Collection', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Kenner'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'The Ultra Corps!', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Lanard'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Classic Collection', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Majic Productions'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Convention Exclusive', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Majic Productions'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'G.I. Joe', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Majic Productions'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Best of the West', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Marx'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Legendary Noble Knights', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Marx'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Barbie', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Mattel'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Birthstone Collection', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Mattel'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Bob Mackie Jewel Series', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Mattel'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Dolls of the World', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Mattel'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Hollywood Legends Collection', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Mattel'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Mad Men', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Mattel'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Max Steel', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Mattel'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'The Frank Sinatra Collection', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Mattel'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Timeless Treasures', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Mattel'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Real Action Heroes', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Medicom'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Star Wars', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Medicom'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, '40th Anniversay Edition', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Modeller''s Loft'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Action Man', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Modeller''s Loft'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Famous British Regiments/Uniforms', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Modeller''s Loft'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Nostalgic Collection', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Modeller''s Loft'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Sportsman', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Modeller''s Loft'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'The Matrix', NULL FROM manufacturer m WHERE m.manufacturer_name = 'N2 Toys'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Modern Forces Assortment', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Old Joe Infirmary'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Reservoir Dogs', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Palisades'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Action Man', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Palitoy'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Famous British Regiments/Uniforms', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Palitoy'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Captain Action', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Playing Mantis'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Hero Series', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Playing Mantis'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Uniform and Equipment', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Playing Mantis'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Villain Series', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Playing Mantis'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Hammer Films', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Product Enterprises'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Captain Action', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Round 2'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'A Real American Hero', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Sideshow'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Bayonets and Barbed Wire', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Sideshow'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Brotherhood of Arms', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Sideshow'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Cobra Enemy', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Sideshow'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'D.C. Comics', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Sideshow'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'G.I. Joe', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Sideshow'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Get Smart', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Sideshow'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Heroes of the Rebellion', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Sideshow'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Hogan''s Heroes', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Sideshow'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Indiana Jones', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Sideshow'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'James Bond', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Sideshow'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Lords of the Sith', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Sideshow'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Movie Masterpiece Series', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Sideshow'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Order of the Jedi', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Sideshow'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Star Wars', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Sideshow'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Universal Studios Monsters', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Sideshow'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'X-Files', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Sideshow'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Young Frankenstein', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Sideshow'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Cool Girls', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Takara'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'G.I. Jane', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Toys McCoy'
INSERT INTO series (manufacturer_id, series_name, series_description) SELECT m.manufacturer_id, 'Americans of Valor', NULL FROM manufacturer m WHERE m.manufacturer_name = 'Valor USA'

----------------------------------------------------------------------------------------------------
-- POST-LOAD VERIFICATION SECTION
-- Select the raw table data and then also do a joined select to get something more easily
-- human-verifiable where the manfucturer's name, not just identifier is output.
----------------------------------------------------------------------------------------------------

SELECT * from series;
GO

SELECT m.manufacturer_name, s.series_description, s.series_name
FROM series s
JOIN manufacturer m ON m.manufacturer_id = s.manufacturer_id;
GO