--------------------------------------------------------------------------------
-- Stgart with a fresh, empty table
DELETE FROM product
GO

--------------------------------------------------------------------------------
-- Create a variable for the 1:6 action figure type. This is the only type of
-- product we will be loading at this point.
--
DECLARE @OneSixthFigureType VARCHAR(128)
SELECT @OneSixthFigureType = product_type.product_type_id         
FROM product_type         
WHERE product_type.product_type_name = '1:6 figure'

--------------------------------------------------------------------------------
-- Insert all the products I currently own. (Well, the majority of them, at
-- least. This DB will help me figure out what I am missing.)
--
INSERT INTO product (product_name, product_type, product_description, year_of_release, purchase_price)
VALUES
('"Screaming Eagle" 101st Airborne (Air Assault), Grenadier, Kevin', @OneSixthFigureType, NULL, 2001, NULL),
('101st Airborne, Corporal "Bud" Norris', @OneSixthFigureType, NULL, 2001, 39.99),
('1st Infantry Division "Big Red One", (Sergeant) "Dave" (Normandy, 1944)', @OneSixthFigureType, 'Collector''s Edition (750) includes Ron Volstad print;', 1999, 41.99),
('20,000 Leagues under the Sea Nautilus Crewman', @OneSixthFigureType, 'Customizer: Greg Eaton;', 2003, NULL),
('2001 A Space Odyssey - Yellow suit', @OneSixthFigureType, 'Box not found;', 2002, NULL),
('2nd British Commando Unit, Private Robert James', @OneSixthFigureType, NULL, 2001, NULL),
('300 King Leonidas', @OneSixthFigureType, NULL, 2010, 149.99),
('3rd Fallschirmjäger Division (Feldwebel), "Meyer" (Ardennes, 1944)', @OneSixthFigureType, NULL, 2001, 39.99),
('5th SF Group Green Berets, Mike', @OneSixthFigureType, NULL, 2001, 34.99),
('6th/7th Battalion Black Watch, 51st (Highland) Division (WWI)', @OneSixthFigureType, NULL, 2001, NULL),
('82nd Airborne Infantry (modern)', @OneSixthFigureType, 'Carded set placed on generic Ultimate Soldier figure;', 1998, 14.99),
('8th Army Rear Honor Guard - Armstrong', @OneSixthFigureType, 'Christmas gift to dada. In shadowbox with watercolor drawing', 2002, NULL),
('A.F.S.O.C. PJ, "Bob"', @OneSixthFigureType, NULL, 2001, 44.99),
('Action Man Crimson Warrior', @OneSixthFigureType, NULL, 1995, NULL),
('Action Marine Beachhead Set', @OneSixthFigureType, 'Set #8; Figure currently used elsewhere; Boots used for Green Beret repro', 2003, NULL),
('Action Marine Communications Set', @OneSixthFigureType, 'Set #3', 2003, NULL),
('Action Marine Dress Parade Set', @OneSixthFigureType, 'Set #11;', 2003, NULL),
('Action Marine Dress Parade Set', @OneSixthFigureType, 'Set #11;', 2003, NULL),
('Action Marine Medic', @OneSixthFigureType, 'Set #9;', 2003, NULL),
('Action Pilot Dress Uniform', @OneSixthFigureType, NULL, 2005, NULL),
('Action Pilot Parade Dress (Vintage)', @OneSixthFigureType, 'Repro tie;', 1964, NULL),
('Action Pilot Survival Set', @OneSixthFigureType, 'Set #4;', 2003, NULL),
('Action Sailor', @OneSixthFigureType, NULL, 1999, NULL),
('Action Sailor Frogman', @OneSixthFigureType, 'Set #2;', 2003, NULL),
('Action Sailor Navy Attack', @OneSixthFigureType, 'Set #7; Needs plastic sailor hat', 2003, NULL),
('Action Soldier (Masterpiece Edition)', @OneSixthFigureType, 'Includes book "G.I. Joe: The Story Behind the Legend."', 1996, 60),
('Action Soldier Accessory Set', @OneSixthFigureType, 'Set #6; Figure currently used elsewhere;', 2003, NULL),
('Action Soldier Combat Attack Set', @OneSixthFigureType, 'Set #1', 2003, NULL),
('Action Soldier Combat Soldier (23rd Set in the Series)', @OneSixthFigureType, NULL, 2005, NULL),
('Action Soldier Military Police', @OneSixthFigureType, 'Set #5;', 2003, NULL),
('Adolph Hitler', @OneSixthFigureType, NULL, 2000, NULL),
('Adventurer (African American)', @OneSixthFigureType, 'AA figure; Includes ATV cloisonne pin;', 2005, 43),
('Aged Adventurer', @OneSixthFigureType, 'Horseshoe baldie;', 2004, 72),
('Air Adventurer', @OneSixthFigureType, 'Life-like hair and beard; "Life-like Hair and Beard" cloisonne pin; Extra head due to hair color problem', 2002, 43),
('Air Force Academy Cadet', @OneSixthFigureType, 'Part of a 2 figure set including American Cadet Alliance Marine', 2002, NULL),
('Air Police', @OneSixthFigureType, NULL, 2004, NULL),
('Airborne at Normandy', @OneSixthFigureType, 'Box not found;', 2000, NULL),
('American Cadet Alliance Marine', @OneSixthFigureType, 'Part of a 2 figure set including Air Force Academy Cadet', 2002, NULL),
('Apollo Astronaut', @OneSixthFigureType, 'Packaged in two parts: (1) Figure; (2) Base', 2002, NULL),
('Aqualad for Action Boy', @OneSixthFigureType, 'Mostly vintage; Some pieces are custom or reproduction;', 1967, NULL),
('Aquaman', @OneSixthFigureType, NULL, 2006, 59.99),
('Aquaman for Captain Action', @OneSixthFigureType, 'Mostly vintage; Some pieces (trident, gloves, boots) are custom or reproduction;', 1966, NULL),
('Arctic Adventurer', @OneSixthFigureType, 'Free with membership;', 2007, 0),
('Argyll and Sutherland Highlander', @OneSixthFigureType, 'Some reproduction pieces;', 1970, NULL),
('Armored Batman (Batman v. Superman)', @OneSixthFigureType, 'MMS 349', 2016, 249.99),
('Army Football Quarterback', @OneSixthFigureType, NULL, 1998, NULL),
('Army Golden Knight', @OneSixthFigureType, 'AA Figure; Two outfits (black and gold);', 1997, 140),
('Army Weapons Instructor', @OneSixthFigureType, 'Very basic (lame) figure;', 2000, NULL),
('Astronaut (Masterpiece Edition)', @OneSixthFigureType, NULL, 1996, NULL),
('Barbie and Krissy Stroll N'' Play 3-in-1 Fun', @OneSixthFigureType, NULL, 2001, NULL),
('Barbie as Batgirl', @OneSixthFigureType, NULL, 2004, NULL),
('Barbie as Wonder Woman', @OneSixthFigureType, 'DC Comics license;', 1999, NULL),
('Batgirl Classic', @OneSixthFigureType, 'Grey costume', 2007, NULL),
('Batgirl Variant', @OneSixthFigureType, 'Black costume', 2007, NULL),
('Batman', @OneSixthFigureType, 'Grey & black costume', 2006, 69.99),
('Batman', @OneSixthFigureType, NULL, 2014, 199),
('Batman (1989 Version) DX Series (DX09)', @OneSixthFigureType, NULL, 2012, 239.99),
('Batman 1966', @OneSixthFigureType, 'MMS 218', 2014, 204.99),
('Batman Classic', @OneSixthFigureType, 'Grey & blue costume', 2007, 69.99),
('Batman for Captain Action', @OneSixthFigureType, 'Mostly vintage; Some pieces (cape, gloves) are reproduction;', 1966, NULL),
('Battle of Leyte Gulf', @OneSixthFigureType, 'Two American uniforms on separate Joes; Only 1 of 2 Japanese uniforms currently on a Joe;', 2002, NULL),
('Battleship Row Defender', @OneSixthFigureType, 'Includes large .50 caliber anti-aircraft gun;', 2000, NULL),
('Belgian Para-commando', @OneSixthFigureType, NULL, 1997, 0),
('Bernard Law Montgomery', @OneSixthFigureType, NULL, 2009, NULL),
('Betty Draper (Barbie)', @OneSixthFigureType, NULL, 2010, NULL),
('Bizarro', @OneSixthFigureType, NULL, 2008, 69.99),
('Black Canary', @OneSixthFigureType, NULL, 2008, 89.99),
('Black Spider Rendezvous', @OneSixthFigureType, NULL, 2002, NULL),
('Blackhawk Boxed Set', @OneSixthFigureType, 'Comes with carded sets "Air Rescue" and "Ice Troops"; Carded sets on 40th Anniversary G.I. Joes; Licensed product; Hasbro; DC Comics;', 2002, NULL),
('Blade II', @OneSixthFigureType, NULL, 2010, 159.99),
('Blaze', @OneSixthFigureType, NULL, 2000, 23.99),
('Blue Angels 2002, Capt. Rob Ffield, No. 1 Flight Leader', @OneSixthFigureType, NULL, 2002, NULL),
('Bob Hope', @OneSixthFigureType, NULL, 1998, NULL),
('Bob Mackie Diamond Barrbie', @OneSixthFigureType, NULL, NULL, NULL),
('Bob Mackie Emerald Barbie', @OneSixthFigureType, NULL, NULL, NULL),
('Bob Mackie Ruby Barbie', @OneSixthFigureType, NULL, NULL, NULL),
('Boba Fett', @OneSixthFigureType, NULL, 2004, NULL),
('Breakfast at Tiffany''s Holly Golightly', @OneSixthFigureType, NULL, 1998, NULL),
('British Paratrooper', @OneSixthFigureType, NULL, 2002, NULL),
('Brothers in Arms, 1st Infantry Division "Big Red One", Ehlers Brothers', @OneSixthFigureType, 'Walt Ehlers died in the Normandy invasion and was awarded the MOH.', 2003, NULL),
('Bruce Lee - "Game of Death"', @OneSixthFigureType, 'NOTE: Accessories left in original box.', 2006, NULL),
('Bulletman (Vintage)', @OneSixthFigureType, NULL, 1976, NULL),
('Bulletman Parade Dress', @OneSixthFigureType, 'Customizer: Leonard Armstrong;', 2004, NULL),
('Bulletwoman White Wedding', @OneSixthFigureType, 'Customizer: Leonard Armstrong;', 2004, NULL),
('C-3PO', @OneSixthFigureType, NULL, 2015, NULL),
('C.G.B. Spender (AKA, The Cigarette Smoking Man) (Sideshow Excl. Vers.)', @OneSixthFigureType, NULL, 2004, NULL),
('C.S. 57th Virginia Infantry', @OneSixthFigureType, 'Civil War', 2001, NULL),
('Captain Action', @OneSixthFigureType, NULL, 2011, NULL),
('Captain Action', @OneSixthFigureType, NULL, 2011, NULL),
('Captain Action (1st packaging)', @OneSixthFigureType, NULL, 1998, NULL),
('Captain Action Arctic Adventurer', @OneSixthFigureType, NULL, 2012, NULL),
('Captain Action as Adam West Batman', @OneSixthFigureType, 'Customizer: Wes McCue, Classic Plastick;', 2001, NULL),
('Captain Action as Flash Gordon', @OneSixthFigureType, 'Figure used for other outfit. (Adam West??)', 1999, 9.99),
('Captain Action as Spider-Man', @OneSixthFigureType, NULL, 2012, NULL),
('Captain Action as The Lone Ranger (Red & black uniform)', @OneSixthFigureType, 'Figure used for blue Lone Ranger costume;', 1998, 19.99),
('Captain Action as Tonto', @OneSixthFigureType, NULL, 1998, 19.99),
('Captain America - The First Avenger', @OneSixthFigureType, 'World War II Version', 2011, 169.99),
('Catwoman', @OneSixthFigureType, NULL, 2013, 189.99),
('Catwoman ', @OneSixthFigureType, NULL, 2007, 69.99),
('Catwoman Classic', @OneSixthFigureType, NULL, 2010, 64.5),
('Challenge at Hawk River', @OneSixthFigureType, 'White water raft;', 1998, NULL),
('Charlie Chaplin', @OneSixthFigureType, NULL, 2012, 179.99),
('Chewbacca', @OneSixthFigureType, 'MMS 263;Part of a 2 figure set with Han Solo;Episode IV - A New Hope version;Price not included. Total price provide on Han Solo line item', 2015, NULL),
('Chinese MiG Pilot (Korean War), Squad Leader Wang Hai', @OneSixthFigureType, NULL, 2003, NULL),
('Chris Jericho', @OneSixthFigureType, NULL, 2002, NULL),
('Civil War Union Soldier', @OneSixthFigureType, NULL, NULL, NULL),
('Clear Joe with Super Articulated Body', @OneSixthFigureType, 'Free with membership;', 2002, 0),
('Clear Joe with Timeless 40th Anniversary Body', @OneSixthFigureType, 'Free with membership;', 2004, 0),
('Cobra Commander', @OneSixthFigureType, NULL, 2003, NULL),
('Coldstream Guard, Guardsman Malcolm Parks', @OneSixthFigureType, NULL, 2002, NULL),
('Colonel Buzz Aldrin', @OneSixthFigureType, NULL, 1999, NULL),
('Combat Aircrew Pilot (F-14)', @OneSixthFigureType, NULL, 2000, NULL),
('Confederate Soldier', @OneSixthFigureType, NULL, NULL, NULL),
('Continental Color Guard, 3rd U.S. Infantry, "The Old Guard"', @OneSixthFigureType, 'Convention set "General''s Package"', 1999, NULL),
('Convention Exclusive German Desert Set', @OneSixthFigureType, 'Includes Kubelwagon, Field Marshall Erwin Rommel, DAK Infantry figure; Rommel is in box 3.71', 2000, NULL),
('Count Dracula', @OneSixthFigureType, NULL, 2004, 55),
('Counter Culture Adventurer', @OneSixthFigureType, 'Wild flocked hair and chops;', 2003, NULL),
('Crash Crew', @OneSixthFigureType, 'May be reproduction tool belt; No fire extinguisher;', 1966, NULL),
('Creature from the Black Lagoon', @OneSixthFigureType, NULL, 2003, NULL),
('Cricketer', @OneSixthFigureType, NULL, 2006, NULL),
('Crimson Cobra Commander', @OneSixthFigureType, NULL, 2009, 109.99),
('Danger Girl - Abbey Chase', @OneSixthFigureType, NULL, 2002, NULL),
('Danger of the Depths', @OneSixthFigureType, 'AA figure with life-like hair and beard and kung-fu grip; Includes shark; Orange wet suit;', 2002, NULL),
('Darth Maul', @OneSixthFigureType, NULL, 2006, 54.99),
('Darth Vader', @OneSixthFigureType, 'Helmet removes to revela Anakin Skywalker;', 2005, NULL),
('Darth Vader', @OneSixthFigureType, NULL, 2015, 249.99),
('Deep Sea Diver - Danger of the Depths', @OneSixthFigureType, 'Diecast acessories;', 1999, 49.99),
('Delta Soldier', @OneSixthFigureType, 'Includes 35th Anniversary patch', 1999, 27.99),
('Desert Recon', @OneSixthFigureType, NULL, 2002, NULL),
('Don Draper (Ken)', @OneSixthFigureType, NULL, 2010, NULL),
('Donovan McNabb', @OneSixthFigureType, 'Figure is ill proportioned and only 10 inches tall, but some accessories are good for 1:6 scale;', NULL, NULL),
('Dr. Evil', @OneSixthFigureType, NULL, 2012, NULL),
('Dr. Evil', @OneSixthFigureType, NULL, 2012, NULL),
('Dr. Evil as Ming the Merciless, Arch Enemy of Flash Gordon', @OneSixthFigureType, NULL, 1999, 9.99),
('Dr. Evil, Captain Action''s Arch Enemy (1st packaging)', @OneSixthFigureType, 'Large-box style packaging', 1998, NULL),
('Dr. Evil, The Sinister Invader of Earth, Arch Enemy of Captain Action (Retro-style packaging)', @OneSixthFigureType, 'Thin-box, retro style packaging;', 1999, NULL),
('Dr. No - James Bond', @OneSixthFigureType, NULL, 2002, NULL),
('Dracula - Count Dracula', @OneSixthFigureType, NULL, 2001, 24.99),
('Dracula - Renfield', @OneSixthFigureType, NULL, 2001, NULL),
('Dress Marine', @OneSixthFigureType, 'Colton body;', 1996, 19.99),
('Dusty', @OneSixthFigureType, NULL, 2001, NULL),
('Eight Ropes of Danger', @OneSixthFigureType, 'Kung Fu Grip', 2002, NULL),
('Enemy Ace', @OneSixthFigureType, 'Comes with carded sets "Knight of the Sky" and "Duel with the Ace"; "Duel with the Ace" uniform set on 2nd (Dragon?) figure; Licensed product; Hasbro; D.C. Comics', 2003, NULL),
('Enhanced Jane', @OneSixthFigureType, 'Customizer: Mike Cherry;', NULL, NULL),
('Ernie Pyle', @OneSixthFigureType, NULL, 2001, NULL),
('Erwin Rommel', @OneSixthFigureType, 'Rip-off customizer; Long delay and poor product;', 1998, NULL),
('Evel Kneivel (White outfit)', @OneSixthFigureType, NULL, 2013, 79.99),
('F-15C Pilot "Viper"', @OneSixthFigureType, 'Sunglasses broken - need repair;', 2001, 39.99),
('F-15E Pilot', @OneSixthFigureType, NULL, 1996, NULL),
('Famous Type Figure (George Lucas)', @OneSixthFigureType, NULL, 2000, NULL),
('Fidel Casto, El Comandante', @OneSixthFigureType, NULL, 2001, 60),
('Fireman', @OneSixthFigureType, 'Box not found;', 2000, NULL),
('First Order TIE Pilot', @OneSixthFigureType, 'MMS 324', 2015, 199),
('Flash', @OneSixthFigureType, NULL, 2007, 59.99),
('Footlocker and 1964 Action Soldier', @OneSixthFigureType, NULL, 2003, NULL),
('Foreign Adventurer', @OneSixthFigureType, 'Free with membership;', 2006, 0),
('Forrest Gump', @OneSixthFigureType, 'Customizer: Dan Chung;', NULL, NULL),
('Frank Sinatra, The Recording Years', @OneSixthFigureType, NULL, 2000, NULL),
('Frankenstein - Fritz', @OneSixthFigureType, NULL, 2001, 24.99),
('Frankenstein - The Monster', @OneSixthFigureType, NULL, 2000, NULL),
('Frankenstein meets the Wolf Man - The Monster', @OneSixthFigureType, NULL, 2001, NULL),
('Franklin D. Roosevelt', @OneSixthFigureType, NULL, 2002, NULL),
('French Resistance Fighter (Vintage)', @OneSixthFigureType, NULL, 1966, NULL),
('Friendship 7', @OneSixthFigureType, 'Friendship VII space capsule; ', 2000, 65),
('Furniture', @OneSixthFigureType, 'Mr. Bean''s sofa, Don Corleone''s desk chair; FDR''s wheelchair; Charlie Chaplin''s chair; Stalin''s chair', NULL, NULL),
('G.I. Elic', @OneSixthFigureType, 'Customizer: Leonard Armstrong; HFF Souvenier;', 2004, NULL),
('General Colin L. Powell', @OneSixthFigureType, NULL, 1998, NULL),
('General Dwight D. Eisenhower', @OneSixthFigureType, NULL, 1997, NULL),
('General George S. Patton', @OneSixthFigureType, 'Includes dog "Willie"', 1997, NULL),
('General George S. Patton, Jr., Commander, U.S. Third Army', @OneSixthFigureType, NULL, 2004, NULL),
('General of the Army Douglas MacArthur, Medal of Honor Recipient', @OneSixthFigureType, NULL, 2003, NULL),
('George W. Bush Talking Action Figure', @OneSixthFigureType, NULL, 2003, NULL),
('George Washington Talking Action Figure', @OneSixthFigureType, NULL, 2003, 30),
('German SS Officer', @OneSixthFigureType, NULL, 1998, NULL),
('Get Smart - Maxwell Smart', @OneSixthFigureType, NULL, 2002, NULL),
('Get Smart - The Chief', @OneSixthFigureType, NULL, 2002, NULL),
('Go Kart Racer', @OneSixthFigureType, NULL, 2001, NULL),
('Goldfinger - Oddjob', @OneSixthFigureType, NULL, 2003, NULL),
('Green Arrow', @OneSixthFigureType, NULL, 2008, 80),
('Green Beret (reproduction outfit on vintage Action Soldier)', @OneSixthFigureType, 'Vintage figure given to me by John Van Note; Boots from Marine Beachhead set', 2007, 0),
('Green Beret 50th Anniversary Edition', @OneSixthFigureType, 'One figure in 1952 dress outfit; One figure in modern combat outfit;', 2002, NULL),
('Green Beret Machine Gun Outpost Set', @OneSixthFigureType, NULL, 2001, NULL),
('Green Lantern', @OneSixthFigureType, NULL, 2006, 59.99),
('Green Lantern Corps', @OneSixthFigureType, 'Tomar Re; Abin Sur; NautKeLoi; Hal Jordan', 2008, 99.99),
('GSG-9 (Grenz Schutz Gruppe-9, The German Response to Terrorism', @OneSixthFigureType, 'Need better release date confirmation;', 2001, NULL),
('Gunnery Sgt. R. Lee Ermey', @OneSixthFigureType, NULL, 2001, NULL),
('Gunnery Sgt. R. Lee Ermey - Dress Blues', @OneSixthFigureType, 'Talking figure;', 2006, 39.99),
('Han Solo', @OneSixthFigureType, 'MMS 263;Part of a 2 figure set with Chewbacca;Episode IV - A New Hope version', 2015, 479.99),
('Harley Quinn', @OneSixthFigureType, NULL, 2008, 79.99),
('Hermann Göring', @OneSixthFigureType, NULL, 2011, NULL),
('Hero''s Homecoming Navy Sailor', @OneSixthFigureType, NULL, 2002, NULL),
('HJ - Hitler Jugend', @OneSixthFigureType, NULL, 2007, 59.95),
('Hogan''s Heroes - Col. Robert Hogan', @OneSixthFigureType, NULL, 2002, NULL),
('Hogan''s Heroes - Col. Wilhelm Kilnk', @OneSixthFigureType, NULL, 2002, NULL),
('Hogan''s Heroes - Sgt. Hans Schultz', @OneSixthFigureType, NULL, 2002, NULL),
('Home for the Holidays Soldier', @OneSixthFigureType, '"Colton" body;', 1996, NULL),
('Hong Kong Police Special Duties Unit (SDU), "Michael Chan"', @OneSixthFigureType, NULL, 1999, NULL),
('Honor Guard', @OneSixthFigureType, NULL, 2000, 19.99),
('House of Frankenstein - The Monster', @OneSixthFigureType, NULL, 2001, NULL),
('Humphrey Bogart as Rick Blaine from Casablanca', @OneSixthFigureType, 'Customizer: Leonard Armstrong with head by Bryan Pagan;', 2004, NULL),
('IDF Givati Recon', @OneSixthFigureType, NULL, 2003, NULL),
('Imperial Japanese Navy Pilot, Lieutenant Sakae', @OneSixthFigureType, NULL, 2001, NULL),
('Imperial Japanese Navy, Yamamoto Ichiro, Seaman 1st Class', @OneSixthFigureType, NULL, 2002, NULL),
('Indiana Jones', @OneSixthFigureType, NULL, 1999, NULL),
('Indiana Jones - Arnold Toht (Sideshow Exclusive Edition)', @OneSixthFigureType, NULL, 2009, 169.99),
('Indiana Jones Epic Stunt Spectacular', @OneSixthFigureType, 'Includes mummy', 2004, 40),
('Indiana Jones from Raiders of the Lost Ark (Sideshow Exclusive Version)', @OneSixthFigureType, NULL, 2008, NULL),
('Inglorious Basterds: Lt. Aldo Raine', @OneSixthFigureType, NULL, 2010, 151.99),
('Irish Barbie', @OneSixthFigureType, NULL, NULL, NULL),
('Iron Man Mark III', @OneSixthFigureType, NULL, 2008, NULL),
('Jackie Johnson from Sgt. Rock and the Men of Easy Company', @OneSixthFigureType, 'Licensed product; Hasbro;', 2002, NULL),
('James Bond from Dr. No', @OneSixthFigureType, NULL, 1998, NULL),
('Jet', @OneSixthFigureType, 'Purchased complete but loose, no box;', 2000, 14.99),
('Joan Holloway (Barbie)', @OneSixthFigureType, NULL, 2010, NULL),
('Joanna Dark (without armor)', @OneSixthFigureType, NULL, 2000, NULL),
('Joe Cabot', @OneSixthFigureType, NULL, 2001, NULL),
('John F. Kennedy Talking Action Figure', @OneSixthFigureType, NULL, 2003, NULL),
('John F. Kennedy: PT 109 Boat Commander', @OneSixthFigureType, NULL, 1999, NULL),
('Joker', @OneSixthFigureType, NULL, 2008, 89.99),
('Joseph Stalin', @OneSixthFigureType, 'Chair in furniture box', 2011, NULL),
('Karate', @OneSixthFigureType, 'Custom uniform on blonde Dragon body;', 2004, NULL),
('Kato, The Green Hornet''s Sidekick, for Captain Action', @OneSixthFigureType, 'Equipment set put on Captain Action figure from earlier Playing Mantis Kato.', 2000, 10.99),
('Ken as Henry Higgins in My Fair Lady', @OneSixthFigureType, NULL, 1995, 50),
('Kid Action as Robin', @OneSixthFigureType, 'Customizer: Leonard Armstrong;', NULL, NULL),
('Kid Action, The Bold Adventurer Sidekick of Captain Action', @OneSixthFigureType, NULL, 2000, NULL),
('Kriegsmarine Warrant Officer (Stabsbootsmann), Georg (Dieppe, 1942)', @OneSixthFigureType, NULL, 2002, 36),
('Kursk - The Greatest Armored Battle of All Time', @OneSixthFigureType, 'Licensed product; Hasbro; One figure talks in German; One figure talks in Russian;', 2003, NULL),
('Land Adventurer', @OneSixthFigureType, 'Life-like hair and beard; AT logo cloisonne pin', 2000, NULL),
('Leia Organa (from A New Hope)', @OneSixthFigureType, NULL, 2007, 54.99),
('Lex Luthor', @OneSixthFigureType, NULL, 2006, 59.99),
('License to Kill - Franz Sanchez', @OneSixthFigureType, 'Includes Uzi & iguana', 2003, 35.99),
('Lieutenant Col. Teddy Roosevelt', @OneSixthFigureType, 'Also politician;', 1999, NULL),
('Life Guard', @OneSixthFigureType, NULL, 1970, NULL),
('Liverpool Footballer (Soccer Player)', @OneSixthFigureType, NULL, 2006, NULL),
('London After Midnight - The Vampire', @OneSixthFigureType, NULL, 2001, NULL),
('Luke Skywalker (Bespin Outfit) - Battle Damaged figure', @OneSixthFigureType, 'DX07; Display elements in separate bag', 2012, NULL),
('Luke Skywalker (Bespin Outfit) - Regular figure', @OneSixthFigureType, 'DX07; Display elements in separate bag', 2012, NULL),
('Luke Skywalker (from Return of the Jedi)', @OneSixthFigureType, NULL, 2006, NULL),
('Luke Skywalker (fron A New Hope)', @OneSixthFigureType, NULL, 2015, NULL),
('M.O.P.P. Marine', @OneSixthFigureType, NULL, 2000, 24.99),
('Mad Bomber', @OneSixthFigureType, NULL, 2001, NULL),
('Mademoiselle Marie, Underground Demolition Operation Set', @OneSixthFigureType, 'Licensed product; Hasbro;', 2002, NULL),
('Man of Asia', @OneSixthFigureType, 'Flocked Asian head; Dressed in separate Kung Fu outfit', 2008, 0),
('Marilyn Monroe wearing B-15C Flying Jacket at Korea, 1954', @OneSixthFigureType, NULL, 2001, NULL),
('Marine Force Recon, "Sniper"', @OneSixthFigureType, 'Figure has custom facial expression mechanism;', 1999, 29.99),
('Marine Jungle Fighter', @OneSixthFigureType, 'Included shadow box display case;', 1999, NULL),
('Marine Scout Marksman', @OneSixthFigureType, NULL, 2004, NULL),
('Martian Manhunter', @OneSixthFigureType, NULL, 2007, 69.99),
('May Emerald Barbie', @OneSixthFigureType, NULL, 2002, NULL),
('Mechanic - U.S. Army Air Force', @OneSixthFigureType, NULL, 2002, NULL),
('Medal of Honor Recipient Roy P. Benavidez', @OneSixthFigureType, NULL, 2001, NULL),
('Michael Jackson, Thriller Version (Regular Michael)', @OneSixthFigureType, 'Thriller; zombie; ', 2009, 189.99),
('Michael Jackson, Thriller Version (Zombie Michael)', @OneSixthFigureType, 'Thriller; zombie; ', 2009, 189.99),
('Mike Power, Atomic Man (vintage)', @OneSixthFigureType, NULL, 1975, NULL),
('Military Police', @OneSixthFigureType, 'Aqua-tinted outfit; Black & gold helmet; Die-cast machine gun', 2002, NULL),
('Millenium Salute', @OneSixthFigureType, 'Saluting arm;', 1999, NULL),
('Miscellaneous Caucasian Female Figure', @OneSixthFigureType, 'Molded short blonde hair wearing green camo and fingerless gloves;', NULL, 3.99),
('Miscellaneous Caucasian Male Figure', @OneSixthFigureType, 'Blue/black "camo" with part white top and Tron-line helmet; Packaged "H.E.R.O.E.S";', NULL, NULL),
('Miscellaneous Caucasian Male Figure', @OneSixthFigureType, 'Solid green outfit with cheesy camo at the sleeves and Tron-like helmet; Packaged "H.E.R.O.E.S";', NULL, NULL),
('Miscellaneous Caucasian Male Figure', @OneSixthFigureType, 'Green/black "camo" with part white top and camo yarmulke.', NULL, NULL),
('Miscellaneous Caucasian Male Figure', @OneSixthFigureType, 'Blue police-like outfit and blue Tron-like helmet; Packaged "Lieutenant Extreme."', NULL, NULL),
('Miscellaneous Caucasian Male Figure', @OneSixthFigureType, 'Nude Dragon brunette;', NULL, NULL),
('Miss Fear, Sword of the Dragon Set', @OneSixthFigureType, 'Licensed product; Hasbro; Elite Force;', 2003, NULL),
('Mission Space', @OneSixthFigureType, NULL, 2004, 40),
('Mission Splashdown', @OneSixthFigureType, 'Space capsule; White spacesuit + jumpsuit; African American figure', 1998, NULL),
('Mission Splashdown', @OneSixthFigureType, 'Space capsule; White spacesuit + jumpsuit', 1998, NULL),
('Modern Surgical Uniform', @OneSixthFigureType, NULL, 2001, NULL),
('Mountain Climbing', @OneSixthFigureType, NULL, 2000, 9.99),
('Mr Brown', @OneSixthFigureType, NULL, 2001, NULL),
('Mr. Bean', @OneSixthFigureType, 'Sofa in box 4.03', 2015, 203.99),
('Navajo Code Talker', @OneSixthFigureType, 'Talks in both English and Navajo', 1999, NULL),
('Naval Special Warfare Development Group "DEVGRU"', @OneSixthFigureType, NULL, 2003, NULL),
('Navy Crash Crew', @OneSixthFigureType, NULL, 2001, NULL),
('Navy Deep Sea Diver', @OneSixthFigureType, NULL, 2003, NULL),
('Navy Dolphin Handler', @OneSixthFigureType, NULL, 2004, NULL),
('Navy Football Linebacker', @OneSixthFigureType, NULL, 1998, NULL),
('Navy Honor Guard', @OneSixthFigureType, 'Free with Convention General''s Package; Set was uniform on cards only - used available figure;', 2004, 0),
('Navy SEAL Rapid Rappel', @OneSixthFigureType, 'Figure slides down rappel rope;', 2003, NULL),
('Neo', @OneSixthFigureType, NULL, 2000, 18.95),
('Nightwing', @OneSixthFigureType, NULL, 2007, NULL),
('Ninja Showdown Snake Eyes vs Storm Shadow', @OneSixthFigureType, 'Included "Spy Troops - The Movie" DVD', 2003, NULL),
('North American F86 Sabre Pilot (Korean War), Col Walker "Bud" Mahurin (51st FIW)', @OneSixthFigureType, NULL, 2003, NULL),
('North American F86 Sabre Pilot (Korean War), Col Walker "Bud" Mahurin (51st FIW)', @OneSixthFigureType, NULL, 2003, NULL),
('Nosferatu - The Vampyre', @OneSixthFigureType, NULL, 2001, NULL),
('Operation: Midnight Recon', @OneSixthFigureType, NULL, 2000, NULL),
('Osama bin Laden', @OneSixthFigureType, 'Armoury not identified on packaging;', 2003, NULL),
('Pearl Harbor Army Air Corps Pilot Display Set', @OneSixthFigureType, 'Includes 2 die cast fighter planes;', 2000, NULL),
('Perfect Body', @OneSixthFigureType, 'Can be used for customization; Currently in original outfit; ', 2001, 14.99),
('Perilous Rescue (black rubber wetsuit)', @OneSixthFigureType, NULL, 2000, NULL),
('Perils of the Raging Inferno (blond with goatee)', @OneSixthFigureType, '1st of 2 sets', 1999, NULL),
('Perils of the Raging Inferno (Red-head with goatee)', @OneSixthFigureType, '2nd of 2 sets', 1999, NULL),
('Philippine Invader', @OneSixthFigureType, NULL, 2002, 39),
('Pony Express', @OneSixthFigureType, 'Includes horse; Purchased at 2002 Con; Needs new picture;', 2001, NULL),
('Power Girl', @OneSixthFigureType, NULL, 2007, 69.99),
('R2D2', @OneSixthFigureType, NULL, 2015, 149.99),
('RAF Fighter Pilot, Squadron Leader Keith Gordon', @OneSixthFigureType, NULL, 2002, NULL),
('Rapid Fire - Operation: Lion''s Den', @OneSixthFigureType, NULL, 2003, NULL),
('Red Army Rifles NCO (Sergeant), Yuri (Leningrad, 1941)', @OneSixthFigureType, NULL, 2002, NULL),
('Rendezvous at Danger Pass', @OneSixthFigureType, 'With reproduction box;', 2004, NULL),
('Rescue of the Lost Squadron', @OneSixthFigureType, 'Includes dog sled;', 1999, NULL),
('Richard M. Nixon Talking Action Figure', @OneSixthFigureType, NULL, 2003, NULL),
('Righthand Man', @OneSixthFigureType, 'Customizer: Leonard Armstrong; Uses bbi Dusty Rhodes figure with custom clothes;', NULL, NULL),
('Robin Classic', @OneSixthFigureType, NULL, NULL, NULL),
('Robin, The Boy Wonder', @OneSixthFigureType, 'MMS 219', 2014, 189.99),
('Roger Sterling (Ken)', @OneSixthFigureType, 'Received in a gift basket', 2010, NULL),
('Roman First Class Warrior', @OneSixthFigureType, NULL, 1998, NULL),
('Rosie the Riveter', @OneSixthFigureType, NULL, 2002, NULL),
('Royal Canadian Mounted Police (RCMP), John Steele', @OneSixthFigureType, NULL, 2000, NULL),
('Russian MVD "Krechet", "Falcon"', @OneSixthFigureType, 'Russian Special Forces; Needs year of release verified;', 2001, NULL),
('S.S.S.P. Akiko Fuji', @OneSixthFigureType, 'Rooted hair version;', 2003, NULL),
('S.W.A.T. Commander', @OneSixthFigureType, NULL, 1999, 29.99),
('S.W.A.T. Motorcycle and Rider', @OneSixthFigureType, NULL, 2000, 19.99),
('S.W.A.T. Operator, "Jackson"', @OneSixthFigureType, NULL, 2003, NULL),
('Saddam Hussein', @OneSixthFigureType, 'Armoury not identified on packaging; Labeled "Most Wanted II"', 2004, NULL),
('Salute to the Chiefs', @OneSixthFigureType, 'Comes with three uniforms: khaki, dress blues, dress whites;', 2005, NULL),
('Sandbox Exclusive', @OneSixthFigureType, 'Desert adventure outfit on random, bearded figure;', 1998, NULL),
('Santa Suit with Beard', @OneSixthFigureType, 'On Joe Figure;', 2003, NULL),
('SAS (Special Air Service) HALO Troop, Desert Operations', @OneSixthFigureType, NULL, 2002, NULL),
('Scarface - Tony Montana Talking Figure', @OneSixthFigureType, NULL, 2005, NULL),
('Scramble Pilot', @OneSixthFigureType, NULL, 2000, NULL),
('Sea Adventurer', @OneSixthFigureType, 'Life-like hair and beard; Sea sled cloisonne pin', 2003, 43),
('SEAL UDT, "Stingray"', @OneSixthFigureType, NULL, 2001, NULL),
('Search for the Radioactive Satellite', @OneSixthFigureType, 'With reproduction box;', 2004, NULL),
('Search for the Yeti (G.I. Joe figure)', @OneSixthFigureType, NULL, 2002, NULL),
('Search for the Yeti (Yeti Figure)', @OneSixthFigureType, NULL, 2002, NULL),
('Secret Mission to Spy Island', @OneSixthFigureType, NULL, 1999, 19.99),
('Secret of the Mummy''s Tomb (reimagined)', @OneSixthFigureType, 'Includes mummy', 2001, NULL),
('Secret of the Mummy''s Tomb (vintage)', @OneSixthFigureType, 'Vintage figure; Includes mummy and ATV vehicle.', 1970, NULL),
('Selina Kyle', @OneSixthFigureType, NULL, 2013, 225),
('Sgt. Rock', @OneSixthFigureType, NULL, 2009, 90),
('Sgt. Rock Boxed Set - Combat uniform', @OneSixthFigureType, 'Comes with carded sets "Winter Combat" and "U.S. Army EM Uniform"', 2000, NULL),
('Sgt. Rock Boxed Set - Combat uniform', @OneSixthFigureType, 'Comes with carded sets "Winter Combat" and "U.S. Army EM Uniform"; EM uniform set on 2nd custom figure with Bryan Pagan head', 2000, NULL),
('Shazam', @OneSixthFigureType, 'Captain Marvel', 2007, 59.99),
('Sheriff Garrett', @OneSixthFigureType, NULL, 1967, NULL),
('Shuttle Astronaut Robert Crippen', @OneSixthFigureType, NULL, 1997, NULL),
('Sinestro', @OneSixthFigureType, NULL, 2009, 99.99),
('Sir Brandon, The Blue Knight', @OneSixthFigureType, NULL, 2001, NULL),
('Skydive to Danger', @OneSixthFigureType, 'FAO went out of business before this exclusive hit the shelves officially.', 2003, NULL),
('Snake-Eyes (Commando) (Sideshow Exclusive Version)', @OneSixthFigureType, NULL, 2009, NULL),
('Soul of the Dragon', @OneSixthFigureType, 'Anime-like head;', 2004, NULL),
('Spider-Man', @OneSixthFigureType, NULL, 2001, 19.99),
('State Trooper', @OneSixthFigureType, NULL, 1997, NULL),
('Stone Cold Steve Austin', @OneSixthFigureType, NULL, 1999, 10),
('Stormtrooper', @OneSixthFigureType, NULL, 2015, NULL),
('Supergirl Classic', @OneSixthFigureType, NULL, 2009, 89.99),
('Superman', @OneSixthFigureType, NULL, NULL, NULL),
('Superman - The Movie - Superman (Sideshow Exclusive)', @OneSixthFigureType, NULL, 2011, 209.99),
('Superman (Batman v. Superman)', @OneSixthFigureType, 'MMS 343', 2016, 209.99),
('Superman Classic', @OneSixthFigureType, NULL, 2007, 69.99),
('T800 - Terminator 2', @OneSixthFigureType, NULL, 2010, 164.99),
('Talking Action Pilot', @OneSixthFigureType, 'Talking figure; String no longer retracts;', 2000, NULL),
('Talking Action Sailor', @OneSixthFigureType, 'Diecast acessories;', 2002, NULL),
('Talking Action Sailor', @OneSixthFigureType, 'Diecast acessories;', 2002, NULL),
('Talking Adventure Team Commander', @OneSixthFigureType, 'Life-like hair and beard; "I''ve got a tough assignment for you" cloisonne pin; Extra head due to beard sculpt problem', 2003, 53),
('Talking Astronaut', @OneSixthFigureType, 'Reproduction; Talker; White jump suit, hat, snoopy cap, 2 types of boots', 2003, 53),
('Talking Baghdad Bob (Iraqi Minister of Dis-information)', @OneSixthFigureType, NULL, 2004, NULL),
('Talking Howard Dean, Volume 2', @OneSixthFigureType, '"I have a scream" version;', 2004, NULL),
('The Abominable Dr. Phibes', @OneSixthFigureType, NULL, 2005, 59.95),
('The Avengers', @OneSixthFigureType, NULL, 2002, NULL),
('The Battle of Salerno and the Italian Campaign of WWII', @OneSixthFigureType, 'Includes mini Life Magazine', 2001, NULL),
('The Bride of Frankenstein - The Bride', @OneSixthFigureType, NULL, 2001, 25.99),
('The Bride of Frankenstein - The Monster', @OneSixthFigureType, NULL, 2001, 25.99),
('The Dark Knight: Batman - Sonar (DX02)', @OneSixthFigureType, NULL, 2009, 149.99),
('The Dark Knight: The Joker - Gotham City Police (DX01)', @OneSixthFigureType, '2 of 2, Cop outfit; Extra uniform placed on a Hot Toys Tru-type figure with narrow shoulders', 2009, NULL),
('The Dark Knight: The Joker - Gotham City Police (DX01)', @OneSixthFigureType, '1 of 2, Joker outfit', 2009, 159.99),
('The Desert Fox (Generalfeldmarschall), "Rommel" (North Africa, 1942)', @OneSixthFigureType, 'Included display case;', 2001, 45),
('The Flash: The Golden Age', @OneSixthFigureType, NULL, 2009, 99.99),
('The Godfather Don Vito Corleone (Sideshow Exclusive Version)', @OneSixthFigureType, 'Includes chair, cat, backdrop, etc.', 2009, 149.99),
('The Green Hornet for Captain Action', @OneSixthFigureType, 'Equipment set put on Captain Action figure from earlier Playing Mantis Green Hornet.', 2000, NULL),
('The Hunchback of Notre Dame - Quasimodo', @OneSixthFigureType, NULL, 2004, 34.99),
('The Invisible Man - The Invisible Man', @OneSixthFigureType, NULL, 2005, 39.99),
('The Lone Ranger for Captain Action (blue uniform)', @OneSixthFigureType, NULL, 2000, NULL),
('The Mummy - Ardeth Bey', @OneSixthFigureType, NULL, 2004, NULL),
('The Mummy - The Mummy', @OneSixthFigureType, NULL, 2003, NULL),
('The Phantom of the Opera - Mask of the Red Death', @OneSixthFigureType, NULL, 2002, 29.99),
('The Phantom of the Opera - The Phantom', @OneSixthFigureType, NULL, 2001, 24.99),
('The Rocketeer, Ver 2.0', @OneSixthFigureType, NULL, 2006, NULL),
('The Royal Horse Guard (The Blues and Royals)', @OneSixthFigureType, NULL, 2006, NULL),
('The Wolf Man - Bela the Gypsy', @OneSixthFigureType, NULL, 2001, 34.99),
('The Wolf Man - Larry Talbot', @OneSixthFigureType, NULL, 2001, NULL),
('The Wolf Man - Wolf Man', @OneSixthFigureType, NULL, 2001, 24.99),
('Thunderball - James Bond', @OneSixthFigureType, NULL, 2004, 39.99),
('Top Cop', @OneSixthFigureType, 'Box signed by Don Levine', 1998, NULL),
('Top Jake', @OneSixthFigureType, 'Box signed by Don Levine', 1998, NULL),
('Tornado Chaser', @OneSixthFigureType, 'Talking figure;', 2000, NULL),
('Triple H', @OneSixthFigureType, NULL, 2002, NULL),
('Two-Face', @OneSixthFigureType, NULL, 2006, 59.99),
('U-2 Pilot (Captain Bob Chapman)', @OneSixthFigureType, 'May be either Air Force or CIA', 2003, NULL),
('U.S. 101st Airborne, Figuretoy.com Exclusive Version', @OneSixthFigureType, 'Includes camoflauge parachute;', 2003, NULL),
('U.S. 82nd Airborne (female)', @OneSixthFigureType, 'G.I. Jane', 1998, NULL),
('U.S. Air Force Pararescue, Sgt. W. "Bones" Wilson', @OneSixthFigureType, 'Accessories are delicate;', 2002, 39.99),
('U.S. Air Force Pararescue, Sgt. W. "Bones" Wilson', @OneSixthFigureType, 'Accessories are delicate;', 2002, 39.99),
('U.S. Army MP, WWII', @OneSixthFigureType, 'Customizing into L.W. Armstrong Honor Guard', NULL, NULL),
('U.S. Army Special Forces', @OneSixthFigureType, 'Carded set placed on generic Ultimate Soldier figure;', 1997, NULL),
('U.S. Army Special Ops. Sergeant, "Brian" (Kuwait City, 1991, Gulf War 10th Anniversary)', @OneSixthFigureType, NULL, 2001, 39.99),
('U.S. Army Taekwondo Trainer', @OneSixthFigureType, NULL, 2002, NULL),
('U.S. Army Tank Crewman', @OneSixthFigureType, 'Licensed product; Hasbro; White-haired version;', 2004, NULL),
('U.S. Coast Guard', @OneSixthFigureType, NULL, 1998, 5),
('U.S. Marine Corps, Sergeant Dusty Rhodes', @OneSixthFigureType, NULL, 2002, 39.99),
('U.S. Marines, "Russell" (Khe Sanh, 1968)', @OneSixthFigureType, NULL, 2001, 34.99),
('U.S. Military Mission-Oriented Protective Posture (MOPP) (Nuclear, Biological, Chemical (NBC)), "Flip"', @OneSixthFigureType, 'Military branch unspecified - I made it Army;', 2002, NULL),
('U.S. Navy Blue Angel', @OneSixthFigureType, NULL, 1997, NULL),
('U.S. Navy Ordinance', @OneSixthFigureType, NULL, 2004, NULL),
('U.S. Navy SEAL Team 3 Combat Swimmer, "Stan', @OneSixthFigureType, NULL, 2001, NULL),
('U.S. Navy SEAL Team Six, "Steve"', @OneSixthFigureType, NULL, 2000, NULL),
('U.S. Pilot, Lt. "Doc" Miller', @OneSixthFigureType, 'Needs year f release verified;', 2001, 39.99),
('U.S.A.A.F. Bomber Captain, "Skip"', @OneSixthFigureType, NULL, 2001, NULL),
('U.S.A.F. Thunderbirds Pilot, Brian Bishop, Leader', @OneSixthFigureType, NULL, 2001, NULL),
('U.S.M.C. M.O.U.T, "Duane"', @OneSixthFigureType, 'M.O.U.T. = Military Operations on Urban Terrain', 2001, NULL),
('U.S.M.C. Raider', @OneSixthFigureType, NULL, 2004, NULL),
('U.S.M.C. Sniper, "Jack" (Pussan, 1950)', @OneSixthFigureType, NULL, 2000, 39.99),
('Ultraman B Type', @OneSixthFigureType, NULL, 2001, NULL),
('Undercover Agent', @OneSixthFigureType, NULL, 2002, NULL),
('Unknown Heroes of WWII', @OneSixthFigureType, 'Incudes two carded sets - Field Triage, Service Dress; Dress uniforms on add''l figures;', 2004, NULL),
('Unknown Soldier', @OneSixthFigureType, 'Exclusive black trench coat & box version;', 2004, NULL),
('USS Connecticut Crewman SSN-22', @OneSixthFigureType, 'AA figure;', 1998, NULL),
('Vampirella (Asian Edition)', @OneSixthFigureType, NULL, 2017, 144.99),
('Van Helsing - Van Helsing', @OneSixthFigureType, NULL, 2004, NULL),
('Viet Cong Guerrilla', @OneSixthFigureType, NULL, 1998, NULL),
('Vietnam Nurse', @OneSixthFigureType, 'Female figure', 1999, NULL),
('Vietnam Wall Memorial', @OneSixthFigureType, 'Includes illuminated wall;', 2000, NULL),
('Voice FX Duke', @OneSixthFigureType, 'Duke talks soft or loud depending on how hard you press his tummy;', 2004, NULL),
('West Point & Annapolis Cadets', @OneSixthFigureType, 'Two figures; Also includes Navy;', 2001, NULL),
('White Zombie - Murder Legendre', @OneSixthFigureType, NULL, 2001, 29.99),
('Wiking Division Panzer Officer (Urbersturmfüher) "Fritz" (Poland, 1944)', @OneSixthFigureType, NULL, 1999, NULL),
('Wild Bill', @OneSixthFigureType, NULL, 2003, NULL),
('Winston Churchill', @OneSixthFigureType, 'Two hats in H.01', 2013, NULL),
('Wonder Woman', @OneSixthFigureType, NULL, 2009, 79.45),
('World War I German Infantry Senior Corporal 1st Westphalian Regiment', @OneSixthFigureType, 'Club distribution of Hasbro product; No box provided;', 2003, NULL),
('WWII European Theater', @OneSixthFigureType, 'Head is currently off figure but can be replaced;', 2002, 3.48),
('Yoda ', @OneSixthFigureType, NULL, 2011, 74.99),
('Young Frankenstein - Frederick', @OneSixthFigureType, NULL, 2001, NULL),
('Young Frankenstein - Igor', @OneSixthFigureType, NULL, 2001, NULL),
('Young Frankenstein - The Monster', @OneSixthFigureType, NULL, 2001, NULL),
('Zatana', @OneSixthFigureType, NULL, 2009, 90)
GO

SELECT product.product_id, 
	   product.product_name,
	   product.product_type,
	   product.product_description,
	   product.year_of_release, 
	   FORMAT(CAST(product.purchase_price AS MONEY), 'C', 'en-us') cost,
	   --'$'+FORMAT(product.purchase_price,'#,0.00') cost,
	   product.purchased_from_retailer,
	   product.manufacturer_id,
	   product.exclusive
FROM product
GO
